# This Makefile is designed to be simple and readable.  It does not
# aim at portability.  It requires GNU Make.

CLEANFILES = *.o xml_parser.hh xml_parser.cc xml_parser.o xml_parser.xml xml_parser.html xml_parser.gv location.hh position.hh stack.hh xml_scanner.cc

clean:
	@echo "Cleaning up..."
	rm -f $(CLEANFILES)
