# This Makefile is designed to be simple and readable.  It does not
# aim at portability.  It requires GNU Make.

CLEANFILES = *.o xsd_parser.hh xsd_parser.cc xsd_parser.o xsd_parser.xml xsd_parser.html xsd_parser.gv location.hh position.hh stack.hh xsd_scanner.cc

clean:
	@echo "Cleaning up..."
	rm -f $(CLEANFILES)
